export { Banners } from './banners'
export { OurServices } from './ourServices'
export { HowWeWork } from './howWeWork'
export { Price } from './price'
export { HardProject } from './hardProject'
export { ServiceDescription } from './serviceDescription'
